export enum HeadersToCheck {
  CICLO = 'Release',
  SPRINT = 'Sprint',
  FEATURE = 'Feature',
  PARENT = 'Parent',
  BACKLOG_ITEM = 'Backlog item: ',
  NAME = 'Name',
  ESTIMATED = 'Estimated hours',
  REMAINING = 'Remaining hours',
  INVESTED = 'Invested hours',
  PHASE = 'Phase',
  STATUS = 'Status',
  OWNER = 'Owner',
  ASSIGNED = 'Assigned',
  TYPE = 'Type',
  DETECTED_DEFECTS = 'Numero defectos encontrados',
  EFICIENCY = 'efficiency',
}
